language: python
python:
  - "2.7"
  - "3.6"

env:
  - TOX_ENV=django18-pg
  - TOX_ENV=django18-sqlite

# Enable PostgreSQL usage
addons:
  postgresql: "9.3"

# Dependencies
install:
  - pip install tox
  - pip install tox-travis
  - pip install coveralls

# Run tests
script:
  - echo $TOX
  - python main
  - tox

# Run coveralls
after_success:
  coveralls
